name = "CrdtBase"
version = "0.1.0"
defaultTargets = ["CrdtBase"]

[leanOptions]
autoImplicit = false

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "CrdtBase"

[[lean_exe]]
name = "CrdtBaseDRT"
root = "CrdtBase.DiffTest.Main"
